username: admin
password: NokiaSrl1!
insecure: false
skip-verify: true
encoding: json_ietf
timeout: 10s

targets:
  srlswitch:
    address: srlswitch:57400

subscriptions:
  srl-mac-table:
    mode: stream
    stream-mode: on-change
    paths:
      - /network-instance[name=lanswitch]/bridge-table/mac-table/mac[address=*]

outputs:
  maclog:
    type: file
    filename: /data/mac_table_updates.json
    format: json


       
     
