username: admin
password: admin
encoding: json_ietf
skip-verify: true
insecure: true

targets:
  srlswitch:
    address: 192.168.1.10:57400
    username: admin
    password: admin

subscriptions:
  mac-table-sub:
    paths:
      - /network-instance[name=lanswitch]/bridge-table/mac-table/mac[address=*]
    mode: on_change
    stream-mode: stream
    encoding: json_ietf
    sample-interval: 10s
    suppress-redundant: true
    heartbeat-interval: 60s

outputs:
  file_output:
    type: file
    file-name: /data/mac_updates.json
    file-type: json
    format: json
    multiline: true
    indent: "  "
    separator: "\n"
    split-events: false
    add-target: true
