subscriptions:
  mac-table-sub:
    paths:
      - /network-instance[name=lanswitch]/bridge-table/mac-table/mac[address=*]
    mode: stream
    stream-mode: on-change
    sample-interval: 30s

outputs:
  - name: maclog
    type: file
    file-name: /data/mac_table_updates.json
    format: json
    multiline: true
    indent: "  "
    separator: "\n"
    split-events: true
    add-target: true
    target-template: "{{ .Target }}"
