username: admin
password: NokiaSrl1!
insecure: false
skip-verify: true
encoding: json_ietf
timeout: 10s

targets:
  srlswitch:
    address: srlswitch:57400

subscriptions:
  srl-acl-statistics:
    mode: stream
    stream-mode: sample
    sample-interval: 20s
    suppress-redundant: true
    paths:
      - /acl/interface[interface-id=*]/input/acl-filter[name=*][type=*]/entry[sequence-id=100]/statistics/matched-packets

outputs:
  file_output:
    type: file
    filename: /data/acl_statistics.json
    format: json
    split-events: true
